"use client";
import '../globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import SideBar from '@/components/Sidebar'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'VideosHub',
  description: 'Generated by create next app',
}

export default function PagesLayout({ children }) {
  const pathname = usePathname();

  return (
    <>
      <div>
        {(pathname !== '/signup' && pathname !== '/login' && pathname !== '/verifyEmail') && <Header />}
        <div className='flex text-white'>
          {(pathname !== '/signup' && pathname !== '/login' && pathname !== '/verifyEmail') && <SideBar />}
          {children}
        </div>
      </div>
    </>
  )
}
