"use client";
import '../globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import SideBar from '@/components/Sidebar/Sidebar'
import { usePathname } from 'next/navigation'
import { useEffect } from 'react';
import { useAuthContext } from '@/ContextAPI/Context/AuthContext';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'VideosHub',
  description: 'Generated by create next app',
}

export default function PagesLayout({ children }) {
  const pathname = usePathname();
  const { setIsLoggedIn } = useAuthContext();

  useEffect(() => {
    (async () => {
      const hasToken = await axios.get('/api/users/isUserLoggedIn');
      if (hasToken.data) {
        setIsLoggedIn(true);
      }
      else {
        console.log('this is hasToken.data from layout main for false', hasToken.data);
        setIsLoggedIn(false);
      }
    })()
  }, [])

  return (
    <>
      <div className='flex flex-col max-h-screen'>
        {(pathname !== '/signup' && pathname !== '/login' && pathname !== '/verifyEmail' && !pathname.startsWith('/dashboard/')) && <Header />}
        <div className='grid grid-cols-[auto,1fr] flex-grow-1 overflow-auto text-white'>
          {/* <div className='bg-neutral-400'>Sidebar</div> */}
          {(pathname !== '/signup' && pathname !== '/login' && pathname !== '/verifyEmail'&& !pathname.startsWith('/dashboard/')) && <SideBar />}
          {children}
        </div>
      </div>
    </>
  )
}
