import DashboardHeader from '@/components/Dashboard/DashboardHeader'
import SidebarForDashboard from '@/components/Dashboard/SidebarForDashboard'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            <div className='flex flex-col max-h-screen bg-zinc-800'>
                <DashboardHeader />
                <div className='grid grid-cols-[auto,1fr] flex-grow-1 overflow-auto text-white'>
                    <SidebarForDashboard />
                    {children}
                </div>
            </div>
        </>
    )
}