"use client"
import AuthHeader from '@/components/Auth/authHeader'
import BlurBackground from '@/components/Auth/BlurBackground'
import { Inter } from 'next/font/google'
import { useAuthContext } from '@/ContextAPI/Context/AuthContext'
import { useRouter } from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

const metadata = {
    title: 'VideosHub',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    const router = useRouter();
    const { isLoggedIn } = useAuthContext();

    if (isLoggedIn) {
        console.log('already logged in no need to go to the auth pages');
        router.replace('/');
    }

    return (
        <div className='w-full'>
            <div className="text-primary">
                <div className="fixed -z-[1] left-1/3 w-12 top-5 blur-2xl">
                    <BlurBackground blur />
                </div>
                <div className="fixed -z-[1] left-0 w-12 top-0 blur-xl">
                    <BlurBackground blur />
                </div>
                <div className="fixed -z-[1] left-1/3 w-12 top-2/3 blur-2xl">
                    <BlurBackground blur />
                </div>
                <div className="fixed -z-[1] left-2/3 w-12 top-1/3 blur-2xl">
                    <BlurBackground blur />
                </div>
                <div className="fixed -z-[1] left-1/4 w-40 top-1/4 blur-2xl opacity-50">
                    <BlurBackground blur />
                </div>
                <div className="fixed -z-[1] left-1/2 w-32 top-1/2 blur-2xl opacity-60">
                    <BlurBackground blur />
                </div>
                <div className="fixed -z-[1] left-[45%] w-12 top-1/3 blur-2xl">
                    <BlurBackground blur />
                </div>
                <div className="fixed -z-[1] left-3/4 w-60 top-1/3 opacity-20 blur-2xl">
                    <BlurBackground blur />
                </div>
            </div>
            {/* <main> */}
            <AuthHeader />
            <main className='mt-24 px-5'>
                {children}
            </main>

            {/* </main> */}
        </div>
    )
}