import { Inter } from 'next/font/google'
import './globals.css'
import { HomeContextProvider } from '@/ContextAPI/Context/HomeContext'
import { AuthContextProvider } from '@/ContextAPI/Context/AuthContext'
import { ChannelContextProvider } from '@/ContextAPI/Context/ChannelContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'VideosHub',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthContextProvider>
                    <HomeContextProvider>
                        <ChannelContextProvider>
                            {children}
                        </ChannelContextProvider>
                    </HomeContextProvider>
                </AuthContextProvider>
            </body>
        </html>
    )
}